### ISSUE TITLE
使用yolov5xTPH，显存占用过大

### ISSUE THREAD

**Issue by tonyskypc** [Gumpest/YOLOv5-Multibackbone-Compression#11]
runtimeerror:cuda out of memory.tried to allocate 198.75GiB

这个要用这样大的显存才能跑起来，我有4张v100 32G都不行，请问是什么原因。

**Comment by Gumpest** [comment]
您好，请用最新的yaml文件尝试一下；之前yolov5x无法兼容TPH标准结构。

**Comment by tonyskypc** [comment]
就是刚刚用的您的最新代码，yaml看了一下是您4天前提交的那份。

**Comment by Gumpest** [comment]
您好，我今天更新了一下；请git pull一下

**Comment by tonyskypc** [comment]
更新今天最新版本后，已经可以训练起来了，非常感谢作者。
