### ISSUE TITLE
mqbench

### ISSUE THREAD

**Issue by lzrslam** [Gumpest/YOLOv5-Multibackbone-Compression#16]
您好，请问train.py的68-70行调用了mqbench这个文件，工程中好像不存在呀。
方便加个微信吗  17802595956 目前在做这方面的研究，希望向您学习一下。

**Comment by ZLkanyo009** [comment]
git clone https://github.com/ZLkanyo009/MQBench.git
cd MQBench
python setup.py build
python setup.py install

您好，使用上述命令行安装MQBench库就可以了

**Comment by lzrslam** [comment]
> git clone https://github.com/ZLkanyo009/MQBench.git cd MQBench python setup.py build python setup.py install
> 
> 您好，使用上述命令行安装MQBench库就可以了

好的 谢谢您
