### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by qitiandasheng11** [Gumpest/YOLOv5-Multibackbone-Compression#21]
AssertionError: train: No labels in /home/xxx/xxx/xxx/VisDrone2019-DET/VisDrone2019-DET-train/labels.cache.

**Comment by Gumpest** [comment]
您好，重新下载该数据集即可

**Comment by qitiandasheng11** [comment]
> 您好，重新下载该数据集即可

抱歉我手动重新下载好几遍，问题仍然是存在的

**Comment by qitiandasheng11** [comment]
> 您好，重新下载该数据集即可

你好，问题已解决，我手动生成了labels，再运行即可
