### ISSUE TITLE
剪枝后通过tensorrt转engine,精度下降明显

### ISSUE THREAD

**Issue by tonyskypc** [Gumpest/YOLOv5-Multibackbone-Compression#25]
yolov5通过作者介绍的方法和代码，进行剪枝后，精度下降在百分之一个点左右，这是可以接受的，效果还可以，转成onnx后，也略有下降，勉强还可以使用，偶尔有误检。再将onnx转成tensorrt的engine，召回率下降更明显，基本不可用了。
请教，剪枝是导致这个的根本原因吗？

**Comment by tonyskypc** [comment]
补充一下，刚才做了一下实验，将onnx输入尺寸和测试尺寸还原到原来pt模型同样大小，onnx是精度没有问题的，关键点可能在tensorrt的engine转换这一块，对剪枝后的网络，是否有一这的影响？

**Comment by wyzwyzzzzz** [comment]
请问你是怎么做到下降在百分之一个点左右的，我用自己的数据集训练了一个V5S的网络，然后用eagleeye.py这个脚本对网络进行剪枝，结果剪枝后的map都是接近于0的，请问是我的哪一步出现了问题了吗

**Comment by tonyskypc** [comment]
@wyzwyzzzzz 用作者提供，带有参数的网络结构来训练。

**Comment by wyzwyzzzzz** [comment]
请问您说的是哪个yaml文件呢，我看作者提供的都是和官网一样的，就用了官网的v5s的pt文件和yaml来进行训练，并没有看到作者提供的pt文件呀

**Comment by tonyskypc** [comment]
@wyzwyzzzzz models/prunmodels/yolov5s-prun.yaml

**Comment by tonyskypc** [comment]
@Gumpest 大佬，剪枝后的模型，在tensorrt转engine的精度明显损失的问题，能否帮忙解答一下。

**Comment by wyzwyzzzzz** [comment]
我之前下载的代码都没有这个yaml文件，那请问你用的预权重pt文件是哪个呢

**Comment by tonyskypc** [comment]
@wyzwyzzzzz git pull更新，不需要预权重，自己训练，训练样本在1000张以上，框在1w个以上，就可以。数据量太小效果不明显。

**Comment by Gumpest** [comment]
> yolov5通过作者介绍的方法和代码，进行剪枝后，精度下降在百分之一个点左右，这是可以接受的，效果还可以，转成onnx后，也略有下降，勉强还可以使用，偶尔有误检。再将onnx转成tensorrt的engine，召回率下降更明显，基本不可用了。 请教，剪枝是导致这个的根本原因吗？

您好，已对剪枝进行了测试，发现v6架构下需要对anchor手动赋值，这可能会影响精度；目前已经修复，请git pull

**Comment by tonyskypc** [comment]
谢谢大佬，您 辛苦了，最近算力紧急，在紧急上模型，还没有精力做剪枝优化，等训练资源出来了，马上来验证，再给您反馈。

**Comment by inSight-mk1** [comment]
@tonyskypc 你好，请问你是如何将TPH的模型转为onnx的？尝试过项目中的export.py，似乎是从和yolov5仓库中的一样，转换onnx时失败

**Comment by tonyskypc** [comment]
@inSight-mk1 不好意思，我没有将TPH转onnx，是自己的网络模型来做的。
