### ISSUE TITLE
TPH-yolov5中只有CBAM模块，而代码中添加了CBAM模块和SeBlock,SeBlock在这的作用是什么

### ISSUE THREAD

**Issue by 18789447455** [Gumpest/YOLOv5-Multibackbone-Compression#3]

**Comment by Gumpest** [comment]
您好，TPH-yolov5只使用了CBAM模块，seblock是用于轻量化模型的（例ghostnet、shufflenet以及mobilenet）

**Comment by 18789447455** [comment]
> 您好，TPH-yolov5只使用了CBAM模块，seblock是用于轻量化模型的（例ghostnet、shufflenet以及mobilenet）
好的，谢谢
