### ISSUE TITLE
ShuffleNetV2预训练模型

### ISSUE THREAD

**Issue by GitHubjinliu** [Gumpest/YOLOv5-Multibackbone-Compression#31]
非常感谢您的工作对我的帮助！请问，您现在是否有ShuffleNetV2预训练模型？

**Comment by Gumpest** [comment]
您好，有在Visdrone下训练的预训练模型。最近会上传至网盘。

**Comment by Gumpest** [comment]
https://disk.pku.edu.cn/link/A5ED89B7B190FCF1C8187A0A8AF20C4F

**Comment by GitHubjinliu** [comment]
Thanks a lot!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Gumpest/YOLOv5-Multibackbone-Compression"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月6日(星期一) 下午5:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Gumpest/YOLOv5-Multibackbone-Compression] ShuffleNetV2预训练模型 (Issue #31)





 
https://disk.pku.edu.cn/link/A5ED89B7B190FCF1C8187A0A8AF20C4F
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
