### ISSUE TITLE
您好，请问您修改主干网络的预训练模型是从哪里获取的，可以分享一下吗，感激！！！！！！！！！！！！

### ISSUE THREAD

**Issue by weijie1111** [Gumpest/YOLOv5-Multibackbone-Compression#32]
修改后没有预训练模型，或许您可以分享嘛 2643946768@qq.com 谢谢。您的轻量型预训练网络模型

**Comment by Gumpest** [comment]
您好，我是从头开始训练的

**Comment by weijie1111** [comment]
可以分享一下您的轻量化网络的预训练模型吗，我设备不行，想用一下您的，可以吗！！！！！！！！！！感激

**Comment by linklist2** [comment]
@Gumpest 您好，请问您是直接在自己的数据集上从头训练的吗，我替换mobilenetv3后直接训练DIOR数据集，效果不太好，比加载mobilenetv3在imagenet上的预训练权重，然后再训练差了五六个点。

**Comment by Gumpest** [comment]
> 可以分享一下您的轻量化网络的预训练模型吗，我设备不行，想用一下您的，可以吗！！！！！！！！！！感激

请问需要哪一个的预训练模型

**Comment by weijie1111** [comment]
> > 可以分享一下您的轻量化网络的预训练模型吗，我设备不行，想用一下您的，可以吗！感激
> 
> 请问需要哪一个的预训练模型

moilenetv3-yolov5,ghostnet-yolov5，这俩，谢谢！！

**Comment by weijie1111** [comment]
moilenetv3-yolov5,ghostnet-yolov5，这俩，谢谢！

**Comment by XhHello** [comment]
>大佬，请问你是在自己数据集上从头训练的吗，不是在Imagenet数据集上的吗，那请问效果相比较于加载了预训练模型，是变好了，还是变差了

**Comment by XhHello** [comment]
> > 可以分享一下您的轻量化网络的预训练模型吗，我设备不行，想用一下您的，可以吗！！！！！！！！！！感激
> 
> 请问需要哪一个的预训练模型
大佬，你好，你修改的moilenetv3-YOLOv5的有在Imagenet数据集训练吗。能否发一个预训练模型，我的邮箱1757030891@qq.com

**Comment by XhHello** [comment]
> @Gumpest 您好，请问您是直接在自己的数据集上从头训练的吗，我替换mobilenetv3后直接训练DIOR数据集，效果不太好，比加载mobilenetv3在imagenet上的预训练权重，然后再训练差了五六个点。

你好，你上面这段话中说的:"加载mobilenetv3在imagenet上的预训练权重"，是你在训练的时候不是加载的yolo.pt，而是加载的mobilenetv3网络的预训练权重吗

**Comment by XhHello** [comment]
> > > 可以分享一下您的轻量化网络的预训练模型吗，我设备不行，想用一下您的，可以吗！感激
> > 
> > 
> > 请问需要哪一个的预训练模型
> 
> moilenetv3-yolov5,ghostnet-yolov5，这俩，谢谢！！

请问你收到这两模型的 权重文件了吗，能否发我一份，邮箱1757030891@qq.com

**Comment by Gumpest** [comment]
> moilenetv3-yolov5,ghostnet-yolov5，这俩，谢谢！

您好，已经更新至对应项中，上传至网盘
