### ISSUE TITLE
您好，请问下hyp文件怎么选择吗或者您设置的来源？

### ISSUE THREAD

**Issue by xuexi123321** [Gumpest/YOLOv5-Multibackbone-Compression#33]
![image](https://user-images.githubusercontent.com/74256726/145021158-33cf4a6a-92a9-49df-b8d9-4a592aef12f4.png)
我看您新添加了一些hyp文件，里面有所更改。

**Comment by Gumpest** [comment]
来源于官方的TPH-YOLO
