### ISSUE TITLE
对models/yolo_quantize.py文件的使用疑惑 

### ISSUE THREAD

**Issue by XhHello** [Gumpest/YOLOv5-Multibackbone-Compression#35]
大佬，请问这个文件的作用是啥啊，该如何使用啊，是量化用的吗

**Comment by ZLkanyo009** [comment]
你好，是量化时使用的，在使用MQBench量化时（具体看README中的使用方式），会调用这个文件，目的是去除yolov5内部本来有的if else判断，防止MQBench做量化结点添加的时候出错。

**Comment by XhHello** [comment]
谢谢大佬的回复，我现在对量化还不懂，问的问题小白了，哈哈




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Gumpest/YOLOv5-Multibackbone-Compression"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月8日(星期三) 上午10:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Gumpest/YOLOv5-Multibackbone-Compression] 对models/yolo_quantize.py文件的使用疑惑  (Issue #35)





 
你好，是量化时使用的，在使用MQBench量化时（具体看README中的使用方式），会调用这个文件，目的是去除yolov5内部本来有的if else判断，防止MQBench做量化结点添加的时候出错。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
