### ISSUE TITLE
您好，使用yolov5mTPH_Standard.yaml的显存溢出报错

### ISSUE THREAD

**Issue by hjq0523** [Gumpest/YOLOv5-Multibackbone-Compression#37]
参数设置，官方预训练模型，batchsize=2，图片大小608
监控了显卡显存是一直积累的。但是使用yolox等训练是没问题的。
大佬，能否看一下报错
autoanchor: Analyzing anchors... anchors/target = 5.85, Best Possible Recall (BPR) = 0.9984
Image sizes 608 train, 608 val
Using 2 dataloader workers
Logging results to runs/train/exp8
Starting training for 10 epochs...

 Epoch   gpu_mem       box       obj       cls    labels  img_size
 0%|                                                                                                                                                 | 0/1834 [00:00<?, ?it/s]

Traceback (most recent call last):
  File "train.py", line 660, in <module>
    main(opt)
  File "train.py", line 557, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 360, in train
    scaler.scale(loss).backward()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/__init__.py", line 130, in backward
    Variable._execution_engine.run_backward(
RuntimeError: CUDA out of memory. Tried to allocate 7.96 GiB (GPU 0; 44.56 GiB total capacity; 32.76 GiB already allocated; 6.46 GiB free; 36.71 GiB reserved in total by PyTorch)

**Comment by Gumpest** [comment]
应该是显存不够 可以尝试一下新的yaml文件: yolov5xP2CBAM-TPH-BiFPN-SPP.yaml
