### ISSUE TITLE
为什么不能使用更高的分辨率输入训练

### ISSUE THREAD

**Issue by XiangqingZhang** [Gumpest/YOLOv5-Multibackbone-Compression#39]
默认训练的输入图片分辨率大小为608，当我采用1280he 1536训练时，都是CUDA out of memory,batch_size 我已经调到最低了，多GPU的batch_size=2，还是bu行，怎么回事啊

**Comment by Gumpest** [comment]
您好，TPU结构yaml文件已经更新，请git pull

**Comment by Gumpest** [comment]
RTX3090是必需的
