### ISSUE TITLE
您好，想问下TPH-yolov5中增加了检测头是不是models下的common.py中的Detection类和Classify类？

### ISSUE THREAD

**Issue by 18789447455** [Gumpest/YOLOv5-Multibackbone-Compression#4]

**Comment by Gumpest** [comment]
您好，增加了检测头具体体现在TPH-YOLOv5的yaml文件中；如下截图部分是多出的P2检测头，负责low-level的小物体检测
![1636428885(1)](https://user-images.githubusercontent.com/56063339/140857416-457a43d6-d615-479b-804e-141f0135ec84.png)
Detection类和Classify类尚未改动，值得一提的是Classify类对应的是二阶段自分类器。

**Comment by 18789447455** [comment]
您好！那我想在YOLOX中加入小物体检测头应该怎么加呢？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月9日(周二) 中午11:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Gumpest/YOLOv5-Multibackbone-Compression] 您好，想问下TPH-yolov5中增加了检测头是不是models下的common.py中的Detection类和Classify类？ (Issue #4)




 
您好，增加了检测头具体体现在TPH-YOLOv5的yaml文件中；如下截图部分是多出的P2检测头，负责low-level的小物体检测
 
 Detection类和Classify类尚未改动，值得一提的是Classify类对应的是二阶段自分类器。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Gumpest** [comment]
您好，在训练脚本中将yolov5x.yaml替换为yolov5xP2.yaml即可，会多出一个P2检测头，只下采样了4倍可以更好地检测小物体。
