### ISSUE TITLE
指标测试问题

### ISSUE THREAD

**Issue by sudospike** [Gumpest/YOLOv5-Multibackbone-Compression#41]
请问一下，你的表格中的指标是在几百张的val集上测的，还是一千多张的那个test-dev集上测的

**Comment by Gumpest** [comment]
![image](https://user-images.githubusercontent.com/56063339/146665216-f9e57b54-5231-4b41-89ea-683a0bb8aa0e.png)
你好，是在验证集上测试的；测试集没有label，无法测试
