### ISSUE TITLE
你好，我在训练自己的数据集的时候遇到了KeyError: 'copy_paste'，如图所示，请问是什么原因呢？

### ISSUE THREAD

**Issue by xyc172** [Gumpest/YOLOv5-Multibackbone-Compression#5]
![127FB`8Q0PXW0C4`N)}7HD2](https://user-images.githubusercontent.com/80620483/141060880-4a1e0b43-c2ed-4418-8c10-886610652b9f.png)

**Comment by Gumpest** [comment]
你好，首先超参数存储于/data/hyps/hyp.scratch.yaml下，第34行的key值为copy_paste，默认值设为0.0，因此你可以尝试直接将p=0.0即可。或者注释这一行。

**Comment by xyc172** [comment]
解决了，十分感谢！
