### ISSUE TITLE
使用yolov5-TPH.yaml训练自己的数据集map很低

### ISSUE THREAD

**Issue by Nicole1233m** [Gumpest/YOLOv5-Multibackbone-Compression#7]
您好，我使用自己的数据集训练，在YOLOv5x上map可以达到80%，但在YOLOv5x-TPH上训练map甚至不到1%，请问这是什么问题？

**Comment by Gumpest** [comment]
您好，请问您的数据集多大呢

**Comment by Nicole1233m** [comment]
> 您好，请问您的数据集多大呢

您好，感谢您的回复！我用的训练集大概200张，测试集60张，是因为数据集过少的原因吗？

**Comment by Gumpest** [comment]
> > 您好，请问您的数据集多大呢
> 
> 您好，感谢您的回复！我用的训练集大概200张，测试集60张，是因为数据集过少的原因吗？

哈哈哈 应该是的；一方面transformer需要大量的数据，一方面模型在继承预训练权重的时候transformer block是没有的。
