### ISSUE TITLE
想问下代码在哪块调用了CBAM 模块

### ISSUE THREAD

**Issue by 18789447455** [Gumpest/YOLOv5-Multibackbone-Compression#8]

**Comment by Gumpest** [comment]
您好，具体在models/common.py文件下，268-270行调用了CBAM模块

**Comment by 18789447455** [comment]
> 您好，具体在models/common.py文件下，268-270行调用了CBAM模块

**Comment by 18789447455** [comment]
> 您好，具体在models/common.py文件下，268-270行调用了CBAM模块

![image](https://user-images.githubusercontent.com/80100005/141727949-620ba75b-018d-454a-86ef-c94b6270ba82.png)
这块应该是transformer吧

**Comment by Gumpest** [comment]
您好，不好意思，我忘记更新了；
这是调用的部分：https://github.com/Gumpest/YOLOv5-Multibackbone-Compression/blob/main/models/yolo.py#L269
这是实现的部分：https://github.com/Gumpest/YOLOv5-Multibackbone-Compression/blob/main/models/common.py#L194
