### ISSUE TITLE
如何与swin结合

### ISSUE THREAD

**Issue by Seperendity** [Gumpest/YOLOv5-Multibackbone-Compression#9]
您好，想请问一下您，如果使用swin transfomer的网络作为检测的主干特征提取网络，您认为会优于目前大部分的主干设计吗？

**Comment by Gumpest** [comment]
您好，这是非常好的提议；Swin Transformer作为ICCV Best Paper，是目前SOTA的backbone，我后续会尝试在YOLOv5中添加Swin Block，我认为会优于目前大部分的主干设计。

**Comment by Seperendity** [comment]
感谢您的回复。之前看到transformer各种刷榜，都开始怀疑卷积会不会慢慢退出了，一直在考虑换主干的效果。还好最近看到RACV2021的讨论会，又对卷积有些信心了哈哈，我会持续关注大佬的实验进展，祝您一切顺利！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Gumpest/YOLOv5-Multibackbone-Compression"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月15日(星期一) 上午9:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Gumpest/YOLOv5-Multibackbone-Compression] 如何与swin结合 (Issue #9)





 
您好，这是非常好的提议；Swin Transformer作为ICCV Best Paper，是目前SOTA的backbone，我后续会尝试在YOLOv5中添加Swin Block，我认为会优于目前大部分的主干设计。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Gumpest** [comment]
好的 谢谢您~

**Comment by XhHello** [comment]
> 感谢您的回复。之前看到transformer各种刷榜，都开始怀疑卷积会不会慢慢退出了，一直在考虑换主干的效果。还好最近看到RACV2021的讨论会，又对卷积有些信心了哈哈，我会持续关注大佬的实验进展，祝您一切顺利！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Gumpest/YOLOv5-Multibackbone-Compression" ***@***.***&gt;; 发送时间:&nbsp;2021年11月15日(星期一) 上午9:56 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Gumpest/YOLOv5-Multibackbone-Compression] 如何与swin结合 (Issue #9) 您好，这是非常好的提议；Swin Transformer作为ICCV Best Paper，是目前SOTA的backbone，我后续会尝试在YOLOv5中添加Swin Block，我认为会优于目前大部分的主干设计。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by XhHello** [comment]
请问你有成功将swin替换为v5的主干了吗

**Comment by Gumpest** [comment]
您好，这个月内会进行替换

**Comment by Gumpest** [comment]
> 请问你有成功将swin替换为v5的主干了吗

已经发布

**Comment by XhHello** [comment]
大佬，您太优秀了，我现在就去瞻仰一番


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Gumpest/YOLOv5-Multibackbone-Compression"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月12日(星期天) 下午3:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Gumpest/YOLOv5-Multibackbone-Compression] 如何与swin结合 (Issue #9)





  
请问你有成功将swin替换为v5的主干了吗
  
已经发布
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by M-torch** [comment]
> > 请问你有成功将swin替换为v5的主干了吗
> 
> 已经发布
大佬您好，请问如果将yolov5的backbone都换成swin transformer该如何修改yaml文件呢

**Comment by XhHello** [comment]
你好，之前没有将swin加入yolov5中。




梧桐&amp;花叶雨
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Gumpest/YOLOv5-Multibackbone-Compression"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月2日(星期天) 晚上8:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Gumpest/YOLOv5-Multibackbone-Compression] 如何与swin结合 (Issue #9)





   
请问你有成功将swin替换为v5的主干了吗
  
已经发布
 大佬您好，请问如果将yolov5的backbone都换成swin transformer该如何修改yaml文件呢
